
nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./server
    links:
        - redis
    ports:
        - "8080"
node2:
    build: ./server
    links:
        - redis
    ports:
        - "8080"
node3:
    build: ./server
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
kafka:
    build: ./kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
